### ISSUE TITLE
Screenresolution for Sauce not supported

### ISSUE THREAD

**Issue by wswebcreation** [saucelabs/sauce-playwright-runner#103]
According to the docs we can change the screenresolution of the VM that is running the Playwright test. This is failing in Sauce

See this build https://app.eu-central-1.saucelabs.com/builds/vdc-v2/e46c7eed5d3e394fb3f202f4d92894c8

This is my config

```yaml
apiVersion: v1alpha
kind: playwright
showconsolelog: false

# Sauce Labs specific information
sauce:
  region: eu-central-1 # or us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    name: Parallel Playwright with SauceCTL
    tags:
      - playwright
      - Parallel
    build: "Playwright: Parallel test set - $DATE"
  sauceignore: .sauceignore

# Playwright specific information
playwright:
  version: 1.11.1
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: .

suites:
  - name: "Swag Labs Login"
    platformName: windows 10
    screenResolution: "1920x1080"
    params:
      browserName: chromium
      headful: true
    testMatch: "**/login.*"

artifacts:
  download:
    match:
      - '*'
    when: always
    directory: ./artifacts

```
