### ISSUE TITLE
testMatch doesn't accept an array

### ISSUE THREAD

**Issue by wswebcreation** [saucelabs/sauce-playwright-runner#105]
According to the docs we should be able to use an array for `testMatch`, see https://docs.saucelabs.com/testrunner-toolkit/configuration/playwright#testmatch

But this configuration leads to an parsing error

```yaml
apiVersion: v1alpha
kind: playwright
showconsolelog: false

# Sauce Labs specific information
sauce:
  region: eu-central-1 # or us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    name: Parallel Playwright with SauceCTL
    tags:
      - playwright
      - Parallel
    build: "Playwright: Parallel test set - $DATE"
  sauceignore: .sauceignore

# Playwright specific information
playwright:
  version: 1.11.1
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: .

suites:
  - name: "Swag Labs Login"
    platformName: windows 10
    params:
      browserName: chromium
      headful: true
    testMatch: ["**/login.*"]

artifacts:
  download:
    match:
      - '*'
    when: always
    directory: ./artifacts

```

Error

```shell
 yarn test.sauce.ex2.eu
yarn run v1.22.10
warning ../../../../../../package.json: No license field
$ DATE=\"$(date)\" npx saucectl run -c ./.sauce/config-ex2.yml
Running version 0.52.4
11:16:56 ERR failed to execute run command error="failed to parse project config: yaml: unmarshal errors:\n  line 29: cannot unmarshal !!seq into string"
error Command failed with exit code 1.
```
